model:
  latent_dim: 4

training:
  learning_rate: 1e-4
  batch_size: 32
  epochs: 30
  workers: 4
  weight_decay: 0.0000
  gradient_accumulation_steps: 4
  use_schedule: True


dataset: 'FashionMNIST'